# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: howtohp
description:
author:
  name: kymmt
  email: contact@koheiyamamoto.me

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']
exclude: ['vender']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

permalink: pretty

# Markdown library
markdown: kramdown
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   use_coderay: false
#   coderay:
#     coderay_wrap: div
#     coderay_line_numbers: inline
#     coderay_line_numbers_start: 1
#     coderay_tab_width: 4
#     coderay_bold_every: 10
#     coderay_css: style
markdown_ext: .md
#   extensions: ['fenced_code_blocks', 'smart']

pygments: true

# My CONST
url: http:howtohp.com
lsi: true

# Multiple languages
languages: ['ja', 'en']
# If not config, the first of languages will be the default
language_default:   'ja'
fill_default_content: false
